parameters:
    it_blaster.sphinx_search_propel.search.class: ItBlaster\SphinxSearchPropelBundle\Search\Sphinxsearch
    it_blaster.sphinx_search_propel.propel.bridge.class: ItBlaster\SphinxSearchPropelBundle\Bridge\PropelBridge
