services:
    # Search Engine
    it_blaster.sphinx_search_propel.search:
        class: %it_blaster.sphinx_search_propel.search.class%
        file: %it_blaster.sphinx_search_propel.sphinx_api.file%
        arguments:
            - %it_blaster.sphinx_search_propel.searchd.host%
            - %it_blaster.sphinx_search_propel.searchd.port%
            - %it_blaster.sphinx_search_propel.searchd.socket%
        calls:
            - [setBridge, [@it_blaster.sphinx_search_propel.propel.bridge]]

    # Propel Bridge
    it_blaster.sphinx_search_propel.propel.bridge:
        class: %it_blaster.sphinx_search_propel.propel.bridge.class%
        arguments: [@service_container, %it_blaster.sphinx_search_propel.propel.entity_manager%, %it_blaster.sphinx_search_propel.indexes%]

    # Twig extension
    it_blaster.sphinx_search_propel.twig.extension_0:
        class: ItBlaster\SphinxSearchPropelBundle\Twig\SphinxsearchExtension
        arguments: [@it_blaster.sphinx_search_propel.search]
        tags:
            - {name: twig.extension}
